### ISSUE TITLE
Chrome/Lastpass doesn't treat signup form password field as a password field for the purposes of auto generation

### ISSUE THREAD

**Issue by Mailor** [jjcm/soci#38]
Expected behaviour:
Opening password field should prompt chrome/lastpass to generate a new password

Actual behaviour:
Password field is not highlighted by chrome/lastpass as a field to generate a new password

**Comment by jjcm** [comment]
Via Ian: "Ended up using lastpass extension and copied a password out of that, then pasted it in. 
I tihnk my bug is about not knowing there is verification happening on the line item because Then verification seemed to not like it- but then liked it?  Or only appeared after leaving the field but I never did I just click submit. I'll try again"

**Comment by jjcm** [comment]
Fixed in https://github.com/jjcm/soci-frontend/commit/fb245157c678284dbaf95c4a6a003ce42bec6ba3
